FROM ruby:2.1.2

RUN mkdir -p /usr/src/app
RUN mkdir -p /cache/bundler

WORKDIR /usr/src/app

COPY . /usr/src/app

ENV BUNDLE_PATH /cache/bundler
RUN bundle install --jobs `nproc` --system --without test:development

ENV RACK_ENV production
CMD ["bundle",  "exec",  "ruby",  "./update_feeds.rb"]
