FROM ruby:2.1.2

RUN mkdir -p /app

WORKDIR /app

EXPOSE 9292
ENV RACK_ENV production

ADD Gemfile /app/
ADD Gemfile.lock /app/
RUN bundle install --system --jobs `nproc` --without test:development

ADD . /app

CMD ["bundle",  "exec",  "rackup",  "./config.ru"]
