development:
  sessions:
    default:
      database: ljfeed_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: ljfeed_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: ljfeed_production
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] || 'localhost' %>:27017
